# Generated by Django 4.2.5 on 2023-12-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Equipo', max_length=32)),
                ('evento', models.CharField(default='Evento', max_length=32)),
                ('ndueno', models.CharField(default='Nombre del dueño', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre', max_length=32)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamano', models.TextField(default='Tamaño', max_length=150)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre', max_length=32)),
                ('last_name', models.CharField(default='Apellido', max_length=32)),
                ('numero', models.DecimalField(decimal_places=2, max_digits=7)),
                ('posicion', models.CharField(default='Posición', max_length=32)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.equipo')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recargas',
            name='category',
        ),
        migrations.DeleteModel(
            name='Accesorios',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Planes',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Recargas',
        ),
    ]
